name: Build, Scan, and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker image
        run: |
          docker build -t my-app:latest .

      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@v0.0.10
        with:
          image: my-app:latest
          severity: CRITICAL
          exit-code: 1
          scan-type: "image"
        continue-on-error: false

      - name: Push image to ECR
        run: |
          docker tag my-app:latest <aws_account_id>.dkr.ecr.<region>.amazonaws.com/<repository_name>:<tag>
          docker push <aws_account_id>.dkr.ecr.<region>.amazonaws.com/<repository_name>:<tag>
        if: success() 

