name: Build, Scan, and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
        with:
          region: us-east-1  # AWS region set to us-east-1

      - name: Build Docker image
        run: |
          docker build -t myapp:latest .

      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@v0.0.10
        with:
          image: myapp:latest
          severity: CRITICAL
          exit-code: 1
          scan-type: "image"
        continue-on-error: false  # Fail the pipeline if critical vulnerabilities are found

      - name: Tag Docker image
        run: |
          docker tag myapp:latest 343218199136.dkr.ecr.us-east-1.amazonaws.com/myapp:latest

      - name: Push image to ECR
        run: |
          docker push 343218199136.dkr.ecr.us-east-1.amazonaws.com/myapp:latest
        if: success()  # Only push if the Trivy scan was successful
