name: Build, Scan, and Push Docker Image

on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*'  
  pull_request:
    branches:
      - 'master'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read

jobs:
  build_and_scan:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: eu-central-1  

    outputs:
      image-tag: ${{ steps.image-tag.outputs.tag }}
      image-uri: ${{ steps.image-tag.outputs.uri }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Generate Image Tag
      id: image-tag
      run: |
        # Generate a unique image tag using the commit SHA (github.sha)
        IMAGE_TAG="${{ github.sha }}_
